version: "{build}"

environment:
  global:
    GITHUB_TOKEN:
      secure: 3J3HXNPKxCnwyaNtnJAH2xwHg9cG/SEB9YNrBGYoGRQSeNBO19+yVv48x6LfNiA9
    VERBOSE: 1 # Get test logs in output
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - APPVEYOR_BUILD_WORKER_IMAGE: macos
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      MSYSTEM: MSYS
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      MSYSTEM: MINGW64
      # Define _POSIX to get a full set of POSIX signal names from signal.h on mingw (for Bee)
      CPPFLAGS: -D_POSIX
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      MSYSTEM: MINGW32
      # Define _POSIX to get a full set of POSIX signal names from signal.h on mingw (for Bee)
      CPPFLAGS: -D_POSIX

for:
-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
  init:
    - sudo apt-get update
    - sudo apt-get -y install texlive-latex-extra texlive-science texlive-fonts-recommended texlive-fonts-extra tex-gyre help2man latexmk hevea rlwrap gcc-multilib linux-libc-dev:i386
-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: macos
  init:
    - brew install help2man
  cache:
    - '/usr/local/Cellar/'
-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  init:
    - cmd: git config --global core.autocrlf input

test: off

install:
  - sh: export PATH="/usr/local/opt/m4/bin:$PATH"
  - sh: ./build-aux/install-executor
  - sh: if [[ "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu" ]]; then sudo ldconfig; fi
  - cmd: C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S libtool autoconf automake help2man"

build_script:
  - sh: git submodule update --init --recursive && autoreconf -i && ./configure --enable-silent-rules
  - sh: if [[ "$APPVEYOR_BUILD_WORKER_IMAGE" == "macos" ]]; then make check; else make distcheck; fi
  - cmd: C:\msys64\usr\bin\bash.exe -lc "cd c:/projects/pforth && ./build-aux/install-executor --no-sudo"
  - cmd: C:\msys64\usr\bin\bash.exe -lc "cd c:/projects/pforth && git submodule update --init --recursive && autoreconf -fi && ./configure --enable-silent-rules && make check"
