language: c

dist: trusty

addons:
  apt:
    packages:
      - texlive-latex-extra
      - texlive-science
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - help2man
      - latexmk
      - hevea

env:
  - HOST=beetle
  - HOST=smite

os:
  - linux
  - osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install help2man ; fi
  - ./build-aux/install-executor $HOST
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig ; fi

script:
  - autoreconf -i && ./configure --enable-silent-rules --host=$HOST
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make check ; else make distcheck ; fi
