language: c

dist: trusty
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &default_deps
      - texlive-latex-extra
      - texlive-science
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - help2man
      - latexmk
      - hevea
      - gcc-5
# env:
#   global:
#     - VERBOSE=1

matrix:
  include:
    - os: linux
      env:
        - COMPILER=gcc-5
    - os: osx
      osx_image: xcode9.2
    - compiler: gcc
      env:
        - COMPILER=gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_deps
            - [gcc-6]

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install help2man ; fi
  - git clone https://github.com/rrthomas/beetle.git
  - cd beetle
  - git submodule update --init --recursive
  - ./bootstrap && ./configure --enable-silent-rules && make check && sudo make install
  - git clone https://github.com/rrthomas/smite.git
  - cd smite
  - git submodule update --init --recursive
  - ./bootstrap && ./configure --enable-silent-rules && make check && sudo make install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig ; fi
  - cd ..

script:
  - ./bootstrap && ./configure --enable-silent-rules
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make check ; else make distcheck ; fi
