language: c

env:
  global:
    - VERBOSE=1

matrix:
  include:
    - os: linux
      env:
        - BUILD=beetle
      addons:
        apt:
          packages: &default_deps
            - texlive-latex-extra
            - texlive-science
            - texlive-fonts-recommended
            - texlive-fonts-extra
            - help2man
            - latexmk
            - hevea
            - rlwrap
    - os: linux
      env:
        - BUILD=smite
      addons:
        apt:
          packages:
            - *default_deps
    - os: linux
      env:
        - BUILD=arm-riscos
      addons:
        apt:
          packages:
            - qtbase5-dev
            - qtmultimedia5-dev
            - libqt5multimedia5-plugins
    - os: osx
      env:
        - BUILD=beetle
    - os: osx
      env:
        - BUILD=smite

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install help2man; fi
  - ./build-aux/install-executor $BUILD
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi

script:
  - autoreconf -i && ./configure --enable-silent-rules --build=$BUILD
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make check; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then if [[ "$BUILD" == "arm-riscos" ]]; then cd src; make \!pForth/\!TestBuild,feb; cd \!pForth; ./run-rpcemu; else make distcheck; fi; fi
