language: c
dist: bionic
os: linux

env:
  global:
    - VERBOSE=1

addons:
  homebrew:
    packages:
    - help2man
    update: true

jobs:
  include:
    - env:
        - HOST=bee
      addons:
        apt:
          packages: &default_deps
            - texlive-latex-extra
            - texlive-science
            - texlive-fonts-recommended
            - texlive-fonts-extra
            - tex-gyre
            - help2man
            - latexmk
            - hevea
            - rlwrap
            - gcc-multilib
    - env:
        - HOST=bee
        - MINIMAL_PRIMITIVES="CREATE MINIMAL_PRIMITIVES"
      addons:
        apt:
          packages:
            - *default_deps
    - os: osx
      env:
        - HOST=bee

install:
  - ./build-aux/install-executor $BUILD
  - if [[ "$BUILD" != "$HOST" ]]; then ./build-aux/install-executor $HOST; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi

script:
  - autoreconf -i && ./configure --enable-silent-rules --build=$BUILD --host=$HOST BUILD_FLAVOUR=$PFORTH_BUILD_FLAVOUR
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make check; fi
